# Generated by Django 2.2.5 on 2020-03-06 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0004_prestamo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='imprint',
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='status',
            field=models.CharField(blank=True, choices=[('m', 'Mantenimiento'), ('p', 'Prestado'), ('d', 'Disponible'), ('r', 'Reservado')], default='m', help_text='Disponibilidad del libro', max_length=1),
        ),
    ]
